#!/sbin/busybox sh

if [ ! -f /sys/devices/platform/i2c-gpio.15/i2c-15/15-0036/power_supply/fuelgauge/fg_reset_soc ];
then
  echo "Device file not found. Fuel gauge chip cannot be reset."
else
  echo "1" > /sys/devices/platform/i2c-gpio.15/i2c-15/15-0036/power_supply/fuelgauge/fg_reset_soc
  echo "The fuel gauge chip has been reset."
fi
