#!/sbin/busybox sh

if [ "a${2}" != "a" ];then
  scaling_governor="${2}"

  case "${scaling_governor}" in
    performance)
	echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "performance" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
      ;;
    powersave)
	echo "powersave" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "powersave" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
      ;;
    userspace)
	echo "userspace" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "userspace" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
      ;;
    interactive)
	echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "interactive" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
      ;;
    conservative)
	echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "conservative" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
      ;;
    *)
	echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
      ;;
  esac;
fi

echo ${scaling_governor}
