#!/sbin/busybox sh
#

export PATH="/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin"
cd /

# Create basic devices
/sbin/busybox mknod -m 622 /dev/console c 5 1
/sbin/busybox mknod -m 666 /dev/null c 1 3
/sbin/busybox mknod -m 666 /dev/tty c 5 0
/sbin/busybox mknod -m 666 /dev/tty0 c 4 0

# Set console to /dev/console
/sbin/busybox setconsole -r

/sbin/busybox mount -t proc proc /proc
/sbin/busybox mount -t sysfs sysfs /sys
/sbin/busybox mount -o remount,rw /

######################
## Enable Logging?? ##
mv /boot-log.txt /boot-log.bak
/sbin/busybox date >/boot-log.txt
exec >>/boot-log.txt 2>&1
#
echo "Starting System ..."

tar xvf /res/misc/dev.tar

echo "Initial System Check done"

rm -rf /dev/*

exec /init
